title: Indians in Richmond, BC
logo: /assets/img/logo.png
description: "Your go-to online directory for Indian businesses, services, and cultural hotspots in Richmond, BC."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
